### ISSUE TITLE
canAddProperty errors out if the schema has no properties field

### ISSUE THREAD

**Issue by ArthurPBressan** [codecombat/treema#50]
I have a schema that defines a certain object like this:

```json
{
 "type": "object",
 "patternProperties": "<someRegex>",
 "additionalProperties": true
}
```
Notice that there's no `properties` field but there is a `patternProperties` field.

However, when I try to add an object to that node, treema errors out with `Uncaught TypeError: Cannot read property '<property>' of undefined` with the culprit being in the following generated check on the `canAddProperty` method (line 3097 on my file):
```javascript
      if (this.workingSchema.properties[key] != null) {
        return true;
      }
```
I changed the above check to 
```javascript
      if (this.workingSchema.properties && this.workingSchema.properties[key] != null)
``` 
and it worked nicely. I don't coffescript so I can't send a PR with the fix.

**Comment by sderickson** [comment]
Thanks for pointing this out! Added a test and fixed that whole bit of logic.
